services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: fraud-kafka

    ports:
      - "9092:9092"

    environment:
      # Kafka / KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-node development settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Default partition count
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_data:/var/lib/kafka/data

    restart: unless-stopped


  cassandra:
    image: cassandra:5.0.9
    container_name: fraud-cassandra

    ports:
      - "9042:9042"

    environment:
      CASSANDRA_CLUSTER_NAME: fraud-detection-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch

    volumes:
      - cassandra_data:/var/lib/cassandra

    restart: unless-stopped


volumes:
  kafka_data:
  cassandra_data: