"""Gemini-only LLM provider and API regression test suite.

Proves:
- Test 1: Gemini is the configured provider.
- Test 2: Gemini generation is called.
- Test 3: No Ollama provider is instantiated; unsupported providers are rejected.
- Test 4: Gemini failure produces a controlled application error without fallback.
- Test 5: RAG context reaches Gemini prompt.
- Test 6: Transaction-specific context reaches Gemini prompt.
- Test 7: /api/llm/status reports no fallback provider (fallback="none").
- Test 8: /api/llm/chat reports Gemini (llm_provider="gemini").
"""
from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi.testclient import TestClient

from backend.app.chat import AssistantUnavailable, answer_chat
from backend.app.main import create_app
from backend.app.schemas import AssistantChatRequest
from backend.app.storage import Store
from rag.investigation.llm_provider import (
    DEFAULT_GEMINI_MODEL,
    GeminiProvider,
    LLMProviderError,
    create_llm_provider,
    verify_configured_chat_provider,
)


# ============================================================================
# GeminiProvider Unit Tests
# ============================================================================

def test_gemini_requires_the_server_side_api_key(monkeypatch):
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    with pytest.raises(LLMProviderError, match="GEMINI_API_KEY is not configured"):
        GeminiProvider()


def test_gemini_uses_bounded_retries_and_json_chat_config(monkeypatch):
    monkeypatch.setenv("GEMINI_API_KEY", "test-only-key")
    calls = []
    delays = []

    class TemporaryFailure(Exception):
        status_code = 503

    class Models:
        def generate_content(self, **kwargs):
            calls.append(kwargs)
            if len(calls) < 3:
                raise TemporaryFailure()
            return type("Response", (), {"text": '{"answer":"grounded","evidence_ids":[],"uncertainties":[]}'})()

    client = type("Client", (), {"models": Models()})()
    provider = GeminiProvider(client=client, sleep=delays.append)

    response = provider.generate("question", "system")

    assert json.loads(response)["answer"] == "grounded"
    assert len(calls) == 3
    assert delays == [0.5, 1.0]
    assert calls[-1]["model"] == provider.model
    assert calls[-1]["config"].system_instruction == "system"
    assert calls[-1]["config"].response_mime_type == "application/json"


def test_gemini_stops_after_two_retries(monkeypatch):
    monkeypatch.setenv("GEMINI_API_KEY", "test-only-key")
    calls = []
    delays = []

    class TemporaryFailure(Exception):
        status_code = 503

    class Models:
        def generate_content(self, **kwargs):
            calls.append(kwargs)
            raise TemporaryFailure()

    client = type("Client", (), {"models": Models()})()
    provider = GeminiProvider(client=client, sleep=delays.append)

    with pytest.raises(LLMProviderError, match="Gemini endpoint is unavailable"):
        provider.generate("question")

    assert len(calls) == 3
    assert delays == [0.5, 1.0]


# ============================================================================
# Regression Tests (Specification Tests 1 - 8)
# ============================================================================

def test_1_gemini_is_the_configured_provider(monkeypatch):
    """Test 1: Gemini is the configured provider."""
    monkeypatch.setenv("LLM_PROVIDER", "gemini")
    monkeypatch.setenv("GEMINI_API_KEY", "test-key")
    monkeypatch.setattr(
        GeminiProvider,
        "check_connection",
        lambda self: {"provider": "gemini", "model": self.model, "status": "reachable"},
    )
    status = verify_configured_chat_provider()
    assert status["provider"] == "gemini"
    assert status["rag_enabled"] is True


def test_2_gemini_generation_is_called(monkeypatch):
    """Test 2: Gemini generation is called."""
    called = []

    class MockGemini:
        provider = "gemini"
        model = "gemini-test"

        def generate(self, prompt, system_prompt=None):
            called.append((prompt, system_prompt))
            return json.dumps({
                "answer": "Generated by Gemini.",
                "evidence_ids": ["src-1"],
                "uncertainties": [],
            })

    store = SimpleNamespace(
        chat_messages=lambda _: [],
        save_chat_message=lambda *args: None,
    )
    request = AssistantChatRequest(question="How does fraud detection work?")
    evidence = [{"source_type": "fraud_knowledge", "source_id": "src-1", "content": "Rule 1"}]

    result = answer_chat(request, store, provider=MockGemini(), retrieval=lambda *_: (evidence, []))
    assert len(called) == 1
    assert result["llm_provider"] == "gemini"
    assert result["answer"] == "Generated by Gemini."


def test_3_no_ollama_provider_is_instantiated(monkeypatch):
    """Test 3: No Ollama provider is instantiated; unsupported providers are rejected."""
    with pytest.raises(LLMProviderError, match="Gemini is the only supported LLM provider"):
        create_llm_provider("ollama")

    with pytest.raises(LLMProviderError, match="Gemini is the only supported LLM provider"):
        create_llm_provider("llama3.2")

    monkeypatch.setenv("LLM_PROVIDER", "ollama")
    status = verify_configured_chat_provider()
    assert status["status"] == "configuration error"
    assert status["available"] is False
    assert "Gemini is the only supported LLM provider" in status["detail"]


def test_4_gemini_failure_produces_a_controlled_application_error(monkeypatch):
    """Test 4: Gemini failure produces a controlled application error without fallback."""
    class FailingGemini:
        provider = "gemini"
        model = "gemini-test"

        def generate(self, prompt, system_prompt=None):
            raise LLMProviderError("Gemini endpoint is unavailable", "endpoint_unavailable")

    store = SimpleNamespace(
        chat_messages=lambda _: [],
        save_chat_message=lambda *args: None,
    )
    request = AssistantChatRequest(question="Why was this flagged?")

    monkeypatch.setattr("backend.app.chat._provider_chain", lambda _: ([FailingGemini()], []))
    with pytest.raises(AssistantUnavailable, match="Gemini service is unavailable"):
        answer_chat(request, store, retrieval=lambda *_: ([], []))


def test_5_rag_context_reaches_gemini(monkeypatch):
    """Test 5: RAG context reaches Gemini."""
    prompts_captured = []

    class MockGemini:
        provider = "gemini"
        model = "gemini-test"

        def generate(self, prompt, system_prompt=None):
            prompts_captured.append(json.loads(prompt))
            return json.dumps({
                "answer": "Grounded answer.",
                "evidence_ids": ["doc-rbi-123"],
                "uncertainties": [],
            })

    store = SimpleNamespace(
        chat_messages=lambda _: [],
        save_chat_message=lambda *args: None,
    )
    request = AssistantChatRequest(
        question="What is the regulatory rule?",
        include_fraud_knowledge=True,
    )
    evidence = [{
        "source_type": "fraud_knowledge",
        "source_id": "doc-rbi-123",
        "content": {"text": "RBI Master Directions 2024 section 4.1"},
    }]

    answer_chat(request, store, provider=MockGemini(), retrieval=lambda *_: (evidence, []))

    assert len(prompts_captured) == 1
    evidence_sent = prompts_captured[0]["retrieved_evidence"]
    assert any(item["source_id"] == "doc-rbi-123" for item in evidence_sent)


def test_6_transaction_specific_context_reaches_gemini(monkeypatch, tmp_path):
    """Test 6: Transaction-specific context reaches Gemini."""
    prompts_captured = []

    class MockGemini:
        provider = "gemini"
        model = "gemini-test"

        def generate(self, prompt, system_prompt=None):
            prompts_captured.append(json.loads(prompt))
            return json.dumps({
                "answer": "Transaction analyzed.",
                "evidence_ids": ["TX-999"],
                "uncertainties": [],
            })

    store = Store(tmp_path / "test6.sqlite3")
    store.create_batch(
        batch_id="B-1",
        requested_count=1,
        delay=0,
        source="test",
        idempotency_key=None,
        request_hash="hash",
    )
    payload = {
        "transaction_id": "TX-999",
        "event_time": "2026-10-05T00:00:00+00:00",
        "type": "TRANSFER",
        "amount": 500000.0,
        "nameOrig": "ORIG-1",
        "nameDest": "DEST-1",
        "oldbalanceOrg": 500000.0,
        "newbalanceOrig": 0.0,
        "risk_level": "L5",
        "anomaly_score": 0.95,
        "final_risk_action": "CRITICAL_INVESTIGATE",
    }
    store.generated("B-1", 1, payload)
    store.record_decision(payload, "fraud")

    request = AssistantChatRequest(
        question="Why was this transaction flagged?",
        transaction_id="TX-999",
        include_cassandra=False,
        include_fraud_knowledge=False,
        include_paysim_cases=False,
    )

    answer_chat(request, store, provider=MockGemini())

    assert len(prompts_captured) == 1
    prompt_obj = prompts_captured[0]
    assert prompt_obj["transaction_id"] == "TX-999"
    current_tx_evidence = next(
        e for e in prompt_obj["retrieved_evidence"]
        if e["source_type"] == "authoritative_current_transaction"
    )
    assert current_tx_evidence["content"]["amount"] == 500000.0
    assert current_tx_evidence["content"]["risk_level"] == "L5"


def test_7_api_llm_status_reports_no_fallback_provider(monkeypatch, tmp_path):
    """Test 7: /api/llm/status reports no fallback provider."""
    monkeypatch.setenv("LLM_PROVIDER", "gemini")
    monkeypatch.setenv("GEMINI_API_KEY", "")

    app = create_app(db_path=tmp_path / "test7.sqlite3", start_workers=False)
    with TestClient(app) as client:
        res = client.get("/api/llm/status")
        assert res.status_code == 200
        payload = res.json()
        assert payload["provider"] == "gemini"
        assert payload["fallback"] == "none"
        assert payload["rag_enabled"] is True


def test_8_api_llm_chat_reports_gemini(monkeypatch, tmp_path):
    """Test 8: /api/llm/chat reports Gemini."""
    class MockGemini:
        provider = "gemini"
        model = "gemini-test-model"

        def generate(self, prompt, system_prompt=None):
            return json.dumps({
                "answer": "This is a Gemini-generated investigation response.",
                "evidence_ids": [],
                "uncertainties": [],
            })

    monkeypatch.setattr("backend.app.chat._provider_chain", lambda _: ([MockGemini()], []))
    monkeypatch.setattr("backend.app.chat._general_context", lambda _: ([], []))

    app = create_app(db_path=tmp_path / "test8.sqlite3", start_workers=False)
    with TestClient(app) as client:
        res = client.post("/api/llm/chat", json={
            "question": "Explain how the fraud pipeline works.",
            "include_cassandra": False,
            "include_fraud_knowledge": False,
            "include_paysim_cases": False,
        })
        assert res.status_code == 200
        payload = res.json()
        assert payload["llm_provider"] == "gemini"
        assert payload["llm_model"] == "gemini-test-model"
        assert "Gemini-generated" in payload["answer"]
